
eureka:
  client:
    service-url:
      defaultZone: http://loaclhost:8761/eureka/,http://loaclhost:8762/eureka/

  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka
#server:
#  port: 8761
management:
  server:
    servlet:
      context-path: /
